config/routes.rb
Rails.application.routes.draw do

  get 'seasons/new'

  get 'seasons/show'

  root 'home#index'
  get '/touslesmatchs', to: 'home#all_matches', as: 'all_matches'
  get '/touslesclubs', to: 'clubs#all_clubs', as: 'all_clubs'
  get '/allseasons', to: 'seasons#all_seasons', as: 'all_seasons'
  get '/admin', to: 'home#administration', as: 'admin'

  get '/admin/maj_mode', to: 'home#maj_mode_for_matches', as: 'admin_maj_mode'
  get '/admin/maj_tournament_format', to: 'home#maj_tourn_format', as: 'admin_maj_tournament_format'
  get '/admin/maj_teams_status', to: 'home#maj_teams_status', as: 'admin_maj_teams_status'

  get '/classement', to: 'home#leaderboard', as: 'leaderboard'
  get '/randomiser', to: 'matches#randomiser', as: 'alea_match'

  resources :matches do
    collection do
      get 'populate_other_list'
    end
  end

  resources :tournaments
  get '/competitions', to: 'tournaments#all_tournaments', as: 'all_tournaments'
  get '/tournaments/:id/launched', to: 'tournaments#close_inscriptions', as: 'close_inscriptions'
  get '/tournaments/:id/closed', to: 'tournaments#close_tournament', as: 'close_tournament'
  get '/tournaments/:id/opened', to: 'tournaments#open_tournament', as: 'open_tournament'
  get '/all_matches/maj', to: 'matches#maj_tournament_for_matches', as: 'maj_tournament'

=begin
  get '/competitions/maj', to: 'tournaments#migrate_all_existing_matches_to_last_season', as: 'maj_teams_season'
  get '/competitions/maj_stats', to: 'tournaments#migrate_all_player_stats_to_last_season_stats', as: 'maj_seasons_stats'
=end

  resources :teams
  resources :players
  resources :clubs
  resources :comments
  resources :seasons

  devise_for :users,
      path: '',
      controllers: {
         sessions: "users/sessions",
         registrations: "users/registrations" },
      path_names: {
        sign_in: 'login',
        sign_out: 'logout',
        sign_up: 'register',
        edit: 'settings',
      }

end

app/models/club.rb
class Club < ApplicationRecord

  has_many :teams
  validates :name, uniqueness: true

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def all_clubs
    @clubs = Club.all
  end

  def new
    @club = Club.new
  end

  def create
    @club = Club.new(club_params)
    if @club.save
          flash[:success] = "Club créé !"
          redirect_to root_path
    else
      render :action => 'new'
      p "Une erreur existe, veuillez recommencer."
    end
  end

  def edit
    @club = Club.find(params[:id])
  end

  def update
    @club = Club.find(params[:id])
    if @club.update(club_params)
      redirect_to club_path(@club)
  	else
      render 'edit'
    end
  end

  def show
    @club = Club.find(params[:id])
  end

  def destroy
    @club = Club.find(params[:id])
    @club.destroy
    redirect_to root_path
  end


  private
  def club_params
    params.require(:club).permit(:id, :name, :denominateur, :level, :color, :image_url)
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/all_clubs.html.erb
<h1>FIFA 18 - Tous les clubs</h1>

<div class="title_w_bg">Liste des clubs référencés</div>


<table class="scoreboard">
  <tr>
    <th>ID du club</th>
    <th>Det.</th>
    <th>Nom</th>
    <th>Niveau</th>
    <th>Couleur</th>
    <th>Url image</th>
  </tr>
  <br>
  <% if @clubs.count == 0 %>
    <tr> <td> Pas de club enregistré </td> </tr>
  <% else %>
    <% @clubs.order('name ASC').each do |club| %>
    <tr>
        <td><%= link_to club.id, club_path(club) %></td>
        <td><%= club.denominateur %> </td>
        <td><%= club.name %> </td>
        <td><%= club.level %> </td>
        <td style="background-color:<%= club.color%>"></td>
        <td><%= club.image_url %> </td>
        <td><%= link_to "Modifier", edit_club_path(club)%></td>
        <td><% if Team.includes(:clubs).where("club_id = ?", club.id).empty? %>
                <%= link_to 'Supprimer', club_path(club), method: :delete, data: { confirm: 'Etes vous sur ?' }%>
            <% end%>
        </td>

    </tr>
    <% end %>
  <% end %>
</table>

app/views/clubs/edit.html.erb
<h1>Edition du club #<%= @club.id%></h1>

<%= form_for(@club) do |c| %>

  <%= c.label :"Article devant le nom si besoin (Ex: La France) " %>
  <%= c.text_field :denominateur, class: 'form-control'%>
  <br>
  <%= c.label :"Nom du club" %>
  <%= c.text_field :name, class: 'form-control'%>
  <br>
  <%= c.label :"Niveau du club" %>
  <%= c.number_field :level, class: 'form-control', :step => 0.5%>
  <br>
  <%= c.label :"Couleur principale du club" %>
  <%= c.text_field :color, class: 'form-control'%>
  <br><br>

  <%= c.label :"Image victorieuse du club" %>
  <%= c.text_field :image_url, class: 'form-control'%>
  <br><br>

  <%= c.submit "Valider", class: "btn btn-primary" %>
<% end %>

<br><br>
<%= link_to "Retour à la liste des clubs", all_clubs_path %>
<br><%= link_to "Accueil", root_path %>

app/views/clubs/new.html.erb
<h1>Ajouter un nouveau Club</h1>

<%= form_for(@club) do |c| %>

  <%= c.label :"Nom du club" %>
  <%= c.text_field :name, class: 'form-control'%>
  <br><br>
  <%= c.label :"Déterminant (le / la / les)si nécéssaire" %>
  <%= c.text_field :denominateur, class: 'form-control'%>
  <br><br>
  <%= c.label :"Niveau du club" %>
  <%= c.number_field :level, class: 'form-control', :step => 0.5%>
  <br>
  <%= c.label :"Image victorieuse du club" %>
  (chemin url):
  <%= c.text_field :image_url, placeholder: "clubs/", class: 'form-control'%>
  <br><br>
  <%= c.submit "Valider", class: "btn btn-primary" %>
<% end %>

app/views/clubs/show.html.erb
<div class="entete_club" style="background-color:<%= @club.color%>">
  <h1><%= @club.denominateur.nil? ? "" :  @club.denominateur %> <%= @club.name %></h1>
</div>

Niveau du club : <%= @club.level %>
<br>
Image de référence : <%= @club.image_url %>
<br><br>
<% if @club.image_url.empty? %>
  Aucune image
<% else %>
  <%= image_tag(image_path(@club.image_url), size: "624x416") %>
<% end %>

<br><br>

<% if user_signed_in? %>
  <%= link_to "Modifier", edit_club_path(@club) %>
  <br>
  <%= link_to "Retour à la liste des clubs", all_clubs_path %>

<% end %>