config/routes.rb
Rails.application.routes.draw do

  get 'seasons/new'

  get 'seasons/show'

  root 'home#index'
  get '/touslesmatchs', to: 'home#all_matches', as: 'all_matches'
  get '/touslesclubs', to: 'clubs#all_clubs', as: 'all_clubs'
  get '/allseasons', to: 'seasons#all_seasons', as: 'all_seasons'
  get '/admin', to: 'home#administration', as: 'admin'

  get '/admin/maj_mode', to: 'home#maj_mode_for_matches', as: 'admin_maj_mode'
  get '/admin/maj_tournament_format', to: 'home#maj_tourn_format', as: 'admin_maj_tournament_format'
  get '/admin/maj_teams_status', to: 'home#maj_teams_status', as: 'admin_maj_teams_status'

  get '/classement', to: 'home#leaderboard', as: 'leaderboard'
  get '/randomiser', to: 'matches#randomiser', as: 'alea_match'

  resources :matches do
    collection do
      get 'populate_other_list'
    end
  end

  resources :tournaments
  get '/competitions', to: 'tournaments#all_tournaments', as: 'all_tournaments'
  get '/tournaments/:id/launched', to: 'tournaments#close_inscriptions', as: 'close_inscriptions'
  get '/tournaments/:id/closed', to: 'tournaments#close_tournament', as: 'close_tournament'
  get '/tournaments/:id/opened', to: 'tournaments#open_tournament', as: 'open_tournament'
  get '/all_matches/maj', to: 'matches#maj_tournament_for_matches', as: 'maj_tournament'

=begin
  get '/competitions/maj', to: 'tournaments#migrate_all_existing_matches_to_last_season', as: 'maj_teams_season'
  get '/competitions/maj_stats', to: 'tournaments#migrate_all_player_stats_to_last_season_stats', as: 'maj_seasons_stats'
=end

  resources :teams
  resources :players
  resources :clubs
  resources :comments
  resources :seasons

  devise_for :users,
      path: '',
      controllers: {
         sessions: "users/sessions",
         registrations: "users/registrations" },
      path_names: {
        sign_in: 'login',
        sign_out: 'logout',
        sign_up: 'register',
        edit: 'settings',
      }

end

app/models/tournament.rb
class Tournament < ApplicationRecord

  validates :name, presence: true, uniqueness: true
  validates :format, presence: true

  has_many :matches, dependent: :destroy

  has_many :rounds, dependent: :destroy
  accepts_nested_attributes_for :rounds, allow_destroy: true

  has_many :seasons, dependent: :destroy
  accepts_nested_attributes_for :seasons, allow_destroy: true

  has_many :players, :through => :seasons
  accepts_nested_attributes_for :players

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def new
    @tournament = Tournament.new
    2.times do
      season = @tournament.seasons.build
    end
    @tournament.status = "opened"
  end

  def create
    @tournament = Tournament.new(tournament_params)
    if (tournament_params[:win_regular_points].nil? && tournament_params[:lose_regular_points].nil?)
      @tournament.win_regular_points = 0
      @tournament.win_prol_points = 0
      @tournament.win_peno_points = 0
      @tournament.lose_regular_points = 0
      @tournament.lose_prol_points = 0
      @tournament.lose_peno_points = 0
      @tournament.draw_regular_points = 0
    end
    @tournament.finished = false
    @tournament.save
    if @tournament.format == "Coupe"
      @first_round = Round.create(:tournament_id => @tournament.id, :step => "Premier Tour")
      @first_round.save
      p @first_round
        i=1
        @tournament.seasons.each { |s|
          s.init_seat = i
          s.status = "alive"
          s.save
          p s
          r = Roundteam.create(:round_id => @first_round.id, :season_id => s.id)
          p r
          i += 1
        }
    end

    if @tournament.save
      redirect_to all_tournaments_path
    else
      render 'new'
    end
  end

  def edit
    @tournament = Tournament.find(params[:id])

    @tournament_seasons = Season.where(["tournament_id = ?", @tournament.id]).pluck(:player_id)
    @tournament_players = Array.new
    @tournament_seasons.each{|ts|
      @tournament_players << Player.find(ts)
    }
    p @tournament_players
    @available_players = (Player.all - @tournament_players)
    p @available_players
  end

  def update
    @tournament = Tournament.find(params[:id])

    if @tournament.update(tournament_params)

      if @tournament.format == "Coupe" && @tournament.status = "opened"
          @first_round = @tournament.rounds.first
          i=1
          @tournament.seasons.each { |s|
            s.init_seat = i
            s.status = "alive"
            s.save
            p "Hello #{i}"
            p Roundteam.where(["round_id=? and season_id=?", @first_round, s.id])
          if Roundteam.where(["round_id=? and season_id=?", @first_round, s.id]).empty?
            r = Roundteam.create(:round_id => @first_round.id, :season_id => s.id)
            p "Hi #{r}"
          else
            p s.id
          end
          i += 1
        }
      end
      flash[:success] = "Votre compétition #{@tournament.name} a bien été mis à jour !"
      redirect_to all_tournaments_path
    else
      render :action => 'edit'
    end
  end

  def close_inscriptions
    @tournament = Tournament.find(params[:id])
    @tournament.status = "launched"
    c = @tournament.seasons.count
    a = [*1..c]
    p a
    @tournament.seasons.all.each{ |s|
      u = a.sample
      p u
      s.seat = u
      a.delete(u)
      p a
      s.save
    }
    @tournament.save
    redirect_to tournament_path(@tournament)
  end

=begin
  def crea_match_premier_tour
    @tournament.rounds.first.seasons.order(:seat).each_slice(2){ |frspair|
      @match = Match.create(:tournament_id => @tournament.id, :round_id => @tournament.rounds.first.id)
      frspair.each { |frs|
        @match.teams.first
        2.times do
          team = @match.teams.build
        end
      }
    }

  end
=end

  def show
    @tournament = Tournament.find(params[:id])

  end

  def close_tournament
    @tournament = Tournament.find(params[:id])
    @tournament.finished = true
    @tournament.save
    redirect_to tournament_path(@tournament)
  end

  def open_tournament
    @tournament = Tournament.find(params[:id])
    @tournament.finished = false
    @tournament.save
    redirect_to tournament_path(@tournament)
  end

  def all_tournaments
    @tournaments = Tournament.all
  end

  def detach_season
    @tournament = Tournament.find(params[:id])
    season = Season.find(params[:season_id])
    @tournament.seasons.delete(season)
    redirect_to edit_tournament_path
  end


  def find_round
    eq_en_lice = @tournament.seasons.where(["status=?", "alive"]).count
  end

  def destroy
    @tournament = Tournament.find(params[:id])
    @tournament.destroy
    redirect_to all_tournaments_path
  end

=begin
    def maj_tournament_for_matches
      Match.all.each { |m|
        m.tournament_id = Tournament.last.id
        m.save
      }
      redirect_to all_matches_path
    end
    def maj_season_for_players
      if @player.seasons.empty?
      Player.all.each { |pl|
        pl.seasons.build
        pl.seasons.first.tournament_id = Tournament.last.id
        if pl.save
          flash[:success] = "Saison ajoutée !"
        else
          flash[:alert] = "Saison ajoutée !"
          render :action => 'edit'
        end
      }
      end
    end

    def migrate_all_existing_matches_to_last_season
      Team.all.each { |t|
          t.season_id = t.player.seasons.last.id
          t.save
      }
      redirect_to all_tournaments_path
    end
    def migrate_all_player_stats_to_last_season_stats
      Season.all.each { |se|
          se.points = se.player.points
          se.win = se.player.win
          se.win_prol = se.player.win_prol
          se.win_peno = se.player.win_peno
          se.lose = se.player.lose
          se.lose_prol = se.player.lose_prol
          se.lose_peno = se.player.lose_peno
          se.save
      }
      redirect_to all_tournaments_path
    end
=end

  private
  def tournament_params
      params.require(:tournament).permit(:name, :format,
        :win_regular_points, :win_prol_points, :win_peno_points,
        :lose_regular_points, :lose_prol_points, :lose_peno_points,
        :draw_regular_points, seasons_attributes: [:id, :init_seat, :seat, :status, :player_id, :_destroy],
        rounds_attributes: [:id, :step],
        roundteams_attributes: [:id, :round_id, :season_id, :_destroy],
      )
  end


end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_season_fields.html.erb
<tr>
  <td><%= s.collection_select :player_id, Player.all, :id, :pseudo, class: 'form-control', include_blank: "Choisir un joueur" %></td>
  <td><%= s.check_box '_destroy' %></td>
</tr>

app/views/tournaments/all_tournaments.html.erb
<h1>Liste des compétitions réalisées </h1>

<div class="title_w_bg">Compétitions</div>
<br>
<table class="tournament_list">
  <tr>
    <th>Tournoi</th>
    <th>Format</th>
    <th>Statut</th>
    <th>Joueurs</th>
    <th>Matchs</th>
    <% if user_signed_in? && current_user.admin %><th>-</th><% end %>
  </tr>
  <% @tournaments.each do |tournament| %>
  <tr>
    <td><%= link_to tournament.name, tournament_path(tournament) %></td>
    <td><%= tournament.format %></td>
    <td><%= tournament.finished ? "Terminé" : "En cours" %></td>
    <td><%= tournament.players.count %></td>
    <td><%= tournament.matches.count %></td>
    <% if user_signed_in? && current_user.admin %>
    <td><%= link_to 'Supprimer', tournament_path(tournament), method: :delete,
            data: { confirm: 'Etes vous sur ?' }%></td>
    <% end %>
  </tr>
  <% end %>
  <tr>
    <td colspan = 4 class="add_tournament"><%= link_to "Créer une nouvelle compétition", new_tournament_path %></td>
  </tr>
</table>

app/views/tournaments/edit.html.erb
<h1>Edition du tournoi</h1>

<%= form_for(@tournament) do |t| %>

  <div class="field">
    <%= t.label :"Nom du tournoi" %>
    <%= t.text_field :name %>
  </div>
  <div class="field">
    <%= t.label :"Format" %> :<%= @tournament.format %>
  </div>
  <br><br>
  <div class="title_w_bg">Joueurs</div>
  <table>
    <tr>
      <th>Joueurs</th>
      <th>Supprimer</th>
    </tr>
    <br>
    <%= t.fields_for :seasons do |pls| %>
      <%= render 'season_fields', s: pls %>
    <% end %>
  </table>
  <%= link_to_add_player_fields "Ajouter un joueur", t, :seasons %>
  <br>

  <br><br>
  <% if @tournament.format == "Championnat" %>
    <div class="title_w_bg">Règles de la compétition</div>
    <div class="tab_tournament_rules">
        Points pour une victoire (90mn) : <%= @tournament.win_regular_points %>
        <br>Points pour une victoire après prolongations : <%= @tournament.win_prol_points %>
        <br>Points pour une victoire aux pénalties <%= @tournament.win_peno_points %>

        <br>
        <br>Points pour une défaite(90mn) : <%= @tournament.lose_regular_points %>
        <br>Points pour une défaite après prolongations : <%= @tournament.lose_prol_points %>
        <br>Points pour une défaite(90mn) : <%= @tournament.lose_peno_points %>

        <br>
        <br>Points pour un match nul : <%= @tournament.draw_regular_points %>
    </div>
    <br>
  <% end %>

  <div class="actions">
    <%= t.submit "Mettre à jour la compétition" %>
  </div>
<% end %>
<br>
<%= link_to "Retour à la compétition", tournament_path %>

app/views/tournaments/new.html.erb
<h1>Créer une nouvelle compétition</h1>

<%= form_for(@tournament) do |t| %>

  <div class="field">
    <%= t.label :"Nom du tournoi" %>
    <%= t.text_field :name %>
  </div>
  <div class="field">
    <%= t.label :"Type de compétition" %>
    <%= t.select :format, [['Championnat', 'Championnat'], ['Coupe', 'Coupe']], prompt: "Choisir un format" %>

  </div>
  <br><br>
  <div class="title_w_bg">Joueurs</div>
  <br>Ajoutez au moins deux joueurs pour lancer une nouvelle compétition :
  <div class="field">
    <%= t.fields_for :seasons do |pls| %>
      <%= pls.label :"Joueur" %>
      <%= pls.collection_select :player_id, Player.all, :id, :pseudo, class: 'form-control', include_blank: "Choisir un joueur" %>
      <br>
    <% end %>
  </div>
  <br><br>
  <div class="title_w_bg">Règles de la compétition</div>
  <div class="tab_tournament_rules">
    <div class="field">
      <%= t.label :"Points pour une victoire (90mn)" %>
      <%= t.text_field :win_regular_points %>
    </div>
    <div class="field">
      <%= t.label :"Points pour une victoire après prolongations" %>
      <%= t.text_field :win_prol_points %>
    </div>
    <div class="field">
      <%= t.label :"Points pour une victoire aux pénalties"  %>
      <%= t.text_field :win_peno_points %>
    </div>
    <br>
    <div class="field">
      <%= t.label :"Points pour une défaite(90mn)" %>
      <%= t.text_field :lose_regular_points %>
    </div>
    <div class="field">
      <%= t.label :"Points pour une défaite après prolongations" %>
      <%= t.text_field :lose_prol_points %>
    </div>
    <div class="field">
      <%= t.label :"Points pour une défaite aux pénaltys"  %>
      <%= t.text_field :lose_peno_points %>
    </div>
    <br>
    <div class="field">
      <%= t.label :"Points pour un match nul" %>
      <%= t.text_field :draw_regular_points %>
    </div>
  </div>
  <br>
  <div class="actions">
    <%= t.submit %>
  </div>
<% end %>

app/views/tournaments/show.html.erb
<h1>Compétition : <%= @tournament.name %></h1>

<div class="title_w_bg">Format</div>
<%= @tournament.try(:format) %>
<br>

<div class="title_w_bg">Statut</div>
<%= @tournament.finished ? "Terminé" : "Ouvert" %></td>
<%= @tournament.try(:status) == "launched" ? " - En cours" : " - Non commencé"%></td>

<br>
<% if user_signed_in? && current_user.admin %>
  <% if @tournament.finished? %>
    <%= link_to "Réouvrir", open_tournament_path %>
  <% else %>
    <%= link_to "Cloturer", close_tournament_path %>
  <% end %>
<% end %>
<% if user_signed_in? && current_user.admin %>
  <% if @tournament.try(:status) != "lauched" %>
    <br>
    <%= link_to "Lancer le tournoi", close_inscriptions_path %>
  <% end %>
<% end %>

<% if (@tournament.format == "Championnat" || @tournament.format.nil?) %>
  <br><br>
  <div class="title_w_bg">Classement</div>
  <table class="leaderboard">
    <tr>
      <th> </th>
      <th> </th>
      <th>Pts</th>
      <th>J.</th>
      <th>G.</th>
      <th>G.pr</th>
      <th>G.pn.</th>
      <th>N.</th>
      <th>D.</th>
      <th>D.pr</th>
      <th>D.pn.</th>
      <th>bp.</th>
      <th>bc.</th>
      <th class="lb_br">Diff.</th>
    </tr>
    <br>

    <% i = 0
      @tournament.seasons.order(points: :desc).each { |ts|
      i = i+1.to_i
    %>
    <tr>
      <td><%= i %></td>
      <td><%= ts.player.pseudo %></td>
      <td><b><%= ts.points %></b></td>
      <td class="lb_br"><%= ts.teams.count %></td>
      <td><%= ts.win %> </td>
      <td><%= ts.win_prol %> </td>
      <td class="lb_br"><%= ts.win_peno %> </td>
      <td class="lb_br"><%= ts.draw %> </td>
      <td><%= ts.lose %> </td>
      <td><%= ts.lose_prol %> </td>
      <td class="lb_br"><%= ts.lose_peno %> </td>
      <td><%= @bp = Team.all.where("season_id= '#{ts.id}'").sum(:score) %></td>
      <td><%= @bc = (Team.where("season_id= '#{ts.id}'").collect{|a| a.match.teams.collect{|b| b.score}.sum }.sum)-(Team.all.where("season_id= '#{ts.id}'").sum(:score)) %></td>
      <td class="lb_br"><%= @bp-@bc %> </td>

    </tr>
    <% } %>
  </table>

  <div class="title_w_bg">Statistiques : Ratios par match </div>

  <table class="leaderboard">
    <tr>
      <th> </th>
      <th> </th>
      <th>Pts / match</th>
      <th>Matchs<br>joués</th>
      <th>G.</th>
      <th>G.pr</th>
      <th>G.pn.</th>
      <th>N.</th>
      <th>D.</th>
      <th>D.pr</th>
      <th>D.pn.</th>
      <th class="lb_br">Buts /<br>match</th>
      <th class="lb_br">Bc./<br>match</th>
    </tr>
    <br>

    <% i = 0
      @tournament.seasons.order(points: :desc).each do |ts|
      i = i+1.to_i
    %>
      <tr>
        <% if @tournament.matches.count != 0 %>
        <td><%= i %></td>
        <td class="lead_team"><%= ts.player.pseudo %></td>
        <td class="lb_br"><b><%= (ts.points.to_f/ ts.teams.count).round(2)%></b></td>
        <td class="lb_br"><%= ts.teams.count %> </td>
          <% if ts.teams.count != 0 %>
          <td>              <%= number_to_percentage(((100 * ts.win) / ts.teams.count), precision: 0) %> </td>
          <td>              <%= number_to_percentage(((100 * ts.win_prol)/ ts.teams.count), precision: 0) %> </td>
          <td class="lb_br"><%= number_to_percentage(((100 * ts.win_peno) / ts.teams.count), precision: 0) %> </td>
          <td class="lb_br"><%= number_to_percentage(((100 * ts.draw) / ts.teams.count), precision: 0) %> </td>
          <td>              <%= number_to_percentage(((100 * ts.lose) / ts.teams.count), precision: 0) %> </td>
          <td>              <%= number_to_percentage(((100 * ts.lose_prol) / ts.teams.count), precision: 0) %> </td>
          <td class="lb_br"><%= number_to_percentage(((100 * ts.lose_peno) / ts.teams.count), precision: 0) %> </td>
          <td><%= (Team.all.where("season_id= '#{ts.id}'").sum(:score).to_f / ts.teams.count).round(2) %></td>
          <td class="lb_br"><%= (((Team.where("season_id= '#{ts.id}'").collect{|a| a.match.teams.collect{|b| b.score}.sum }.sum)-(Team.all.where("season_id= '#{ts.id}'").sum(:score))).to_f / ts.teams.count).round(2) %></td>
          <% end %>
        <% end %>


      </tr>
    <% end %>

  </table>
<% end %>

<br>
<% if @tournament.format == "Coupe" %>
  <div class="title_w_bg">Liste des joueurs</div>
  <br>
  <% @tournament.players.all.each{ |p| %>
    <%= p.pseudo %>
    <br>
  <% } %>

  <div class="title_w_bg">Tableau</div>
  <% if @tournament.status == "launched" %>
    <div class="cup_round">
      <div><%= @tournament.rounds.first.step %></div>


      <div><%= @tournament.seasons.count %></div>
      <br><br>
      <% @tournament.seasons.order(:seat).all.each_slice(2){ |ss| %>
        <div class="cup_match">
          <% ss.each { |s| %>
          <div class="cup_team"><%= "Siège #{s.seat} #{s.player.try(:pseudo)}" %></div>
          <% } %>
          <div class="match_link">Match
          </div>
        </div>
      <% } %>
    </div>
  <% else %>
    <div><%= @tournament.rounds.first.step %></div>
    <div><% @tournament.rounds.first.seasons.each { |rs| %>
      <%= rs.id %>
    <% } %>
    </div>
    <br>
    <% @tournament.seasons.all.each{ |s| %>
      <div class="cup_team"><%= s.init_seat.nil? ? "Pas de siège défini" :  "Siège #{s.init_seat} #{s.player.try(:pseudo)} #{s.rounds.first.try(:step)}" %></div>
    <% } %>
  <% end %>
<% end %>

<br><br>
<div class="title_w_bg">Matchs</div>
<br>
<table class="scoreboard">

  <tr>
    <th>ID du match</th>
    <th>Mode</th>
    <th>Joueur 1</th>
    <th>Team 1</th>
    <th>Score</th>
    <th>Team 2</th>
    <th>Joueur 2</th>

  </tr>
  <br>

  <% if !@tournament.matches.empty? %>
    <% @tournament.matches.order('id DESC').each do |match| %>

      <tr>
        <td><%= match.id %></td>
        <td><%= match.mode %></td>
        <td><%= link_to Player.find(match.teams.first.player_id).pseudo, player_path(match.teams.first.player_id) %> </td>
        <td><%= match.teams.first.club.name %> </td>
        <td><div class="tab_score">
              <%= match.teams.first.score %> - <%= match.teams.last.score %>
            </div>
            <span class="tab_score_prol">
            <%= (match.prolongations && !match.teams.first.prol_score) ? "a.p" : "" %>
            <%= match.teams.first.prol_score %><%= match.teams.first.prol_score == nil ? '' : ' tab ' %><%= match.teams.last.prol_score %>
            </span>
        </td>

        <td><%= match.teams.last.club.name %> </td>
        <td><%= link_to Player.find(match.teams.last.player_id).pseudo, player_path(match.teams.last.player_id) %> </td>
        <td><%= link_to "Détails", match_path(match)%></td>
      </tr>
      <% end %>

  <% else %>
    Pas de match pour ce tournoi
  <% end %>

</table>
<br>

<% if (@tournament.format == "Championnat" || @tournament.format.nil?) %>

  <div class="title_w_bg">Règles</div>
  <br>Points pour une victoire :
  <br>Sur 90mn : <%= @tournament.win_regular_points %>
  <br>Après prolongations : <%= @tournament.win_prol_points %>
  <br>Aux pénalties : <%= @tournament.win_peno_points %>
  <br><br>
  Points pour une défaite
  <br>90mn : <%= @tournament.lose_regular_points %>
  <br>Après prolongations : <%= @tournament.lose_prol_points %>
  <br>Aux pénaltys : <%= @tournament.lose_peno_points %>

  <br><br>Points pour un match nul : <%= @tournament.draw_regular_points %>

<% end %>

<br><br>
<% if user_signed_in? %>
<%= link_to "Modifier", edit_tournament_path(@tournament)%></td>
<br><br>
<%= link_to 'Supprimer', tournament_path(@tournament), method: :delete, data: { confirm: 'Etes vous sur de supprimer cette compétition et tous ses résultats ?' }%>
<br><br>
<% end %>
<%= link_to "Retour à la liste des compétitions", all_tournaments_path %>