config/routes.rb
Rails.application.routes.draw do

  get 'seasons/new'

  get 'seasons/show'

  root 'home#index'
  get '/touslesmatchs', to: 'home#all_matches', as: 'all_matches'
  get '/touslesclubs', to: 'clubs#all_clubs', as: 'all_clubs'
  get '/allseasons', to: 'seasons#all_seasons', as: 'all_seasons'
  get '/admin', to: 'home#administration', as: 'admin'

  get '/admin/maj_mode', to: 'home#maj_mode_for_matches', as: 'admin_maj_mode'
  get '/admin/maj_tournament_format', to: 'home#maj_tourn_format', as: 'admin_maj_tournament_format'
  get '/admin/maj_teams_status', to: 'home#maj_teams_status', as: 'admin_maj_teams_status'

  get '/classement', to: 'home#leaderboard', as: 'leaderboard'
  get '/randomiser', to: 'matches#randomiser', as: 'alea_match'

  resources :matches do
    collection do
      get 'populate_other_list'
    end
  end

  resources :tournaments
  get '/competitions', to: 'tournaments#all_tournaments', as: 'all_tournaments'
  get '/tournaments/:id/launched', to: 'tournaments#close_inscriptions', as: 'close_inscriptions'
  get '/tournaments/:id/closed', to: 'tournaments#close_tournament', as: 'close_tournament'
  get '/tournaments/:id/opened', to: 'tournaments#open_tournament', as: 'open_tournament'
  get '/all_matches/maj', to: 'matches#maj_tournament_for_matches', as: 'maj_tournament'

=begin
  get '/competitions/maj', to: 'tournaments#migrate_all_existing_matches_to_last_season', as: 'maj_teams_season'
  get '/competitions/maj_stats', to: 'tournaments#migrate_all_player_stats_to_last_season_stats', as: 'maj_seasons_stats'
=end

  resources :teams
  resources :players
  resources :clubs
  resources :comments
  resources :seasons

  devise_for :users,
      path: '',
      controllers: {
         sessions: "users/sessions",
         registrations: "users/registrations" },
      path_names: {
        sign_in: 'login',
        sign_out: 'logout',
        sign_up: 'register',
        edit: 'settings',
      }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Pagy::Backend

  def reset_points
    @players = Player.all
    @players.each do |p|
      p.points = 0
      p.save
    end
  end

  def reset_matches
    Match.all.destroy_all
  end

  def reset_players
    Player.all.destroy_all
  end

  def reset_tournaments
    Tournament.all.destroy_all
  end

  def index
    @matches = Match.all
    @match_une = Match.last

    maj_status_last_match()
    if Match.last.nil?
      p "Pas de last match"
    else
      image_a_la_une()
      gros_titre_a_la_une()
      special_teams()
      special_score()
    end

    @players = Player.all
    @comments = Comment.all
    # reset_points()
    # reset_matches()
    # reset_players()
    # reset_tournaments()
  end


  def all_matches
    @pagy, @matches = pagy(Match.all)
    @players = Player.all
  end

  def leaderboard
    @matches = Match.all
    @players = Player.all
  end

  def maj_status_last_match
    if Match.last.nil?
      p "Pas de last match"
    else
      if Match.last.teams.first.status.nil?
          if ((@match_une.teams.first.score > @match_une.teams.last.score) && !@match_une.prolongations)
              flash[:notice] = "J1 a gagné"
              @match_une.teams.first.update_columns(status: "winner")
              @match_une.teams.last.update_columns(status: "loser")
          elsif ((@match_une.teams.first.score < @match_une.teams.last.score) && !@match_une.prolongations)
              flash[:notice] = "J2 a gagné"
              @match_une.teams.first.update_columns(status: "loser")
              @match_une.teams.last.update_columns(status: "winner")

          elsif @match_une.prolongations && (@match_une.teams.first.score > @match_une.teams.last.score)
              flash[:notice] = "J1 a gagné après prolongations"
              @match_une.teams.first.update_columns(status: "winner")
              @match_une.teams.last.update_columns(status: "loser")
          elsif @match_une.prolongations && (@match_une.teams.first.score < @match_une.teams.last.score)
              flash[:notice] = "J2 a gagné après prolongations"
              @match_une.teams.first.update_columns(status: "loser")
              @match_une.teams.last.update_columns(status: "winner")
          elsif (@match_une.teams.first.score == @match_une.teams.last.score) && (@match_une.teams.first.prol_score > @match_une.teams.last.prol_score)
              flash[:notice] = "J1 a gagné aux tirs au buts."
              @match_une.prolongations = true
              @match_une.teams.first.update_columns(status: "winner")
              @match_une.teams.last.update_columns(status: "loser")
              @match_une.save
          elsif (@match_une.teams.first.score == @match_une.teams.last.score) && (@match_une.teams.first.prol_score < @match_une.teams.last.prol_score)
              flash[:notice] = "J2 a gagné aux tirs au buts."
              @match_une.prolongations = true
              @match_une.teams.first.update_columns(status: "loser")
              @match_une.teams.last.update_columns(status: "winner")
              @match_une.save
          end
      end
    end
  end



  def image_a_la_une
    if !@matches.first.nil?
      if @match_une.teams.first.status == 'draw'
          @image_a_la_une = 'clubs/noclub.jpg'
      elsif @match_une.teams.where("status='winner'").first.club.image_url.nil?
          @image_a_la_une = 'clubs/noclub.jpg'
      elsif !@match_une.teams.where("status='winner'").first.club.image_url.nil?
          @image_a_la_une = @match_une.teams.where("status = 'winner'").first.club.image_url
      end
    end
  end

  def gros_titre_a_la_une
      if !@matches.first.nil?
        if @match_une.teams.first.status == 'draw'
        elsif @match_une.teams.first.status == 'winner'
          @team_grostitre_denominateur = @match_une.teams.first.club.denominateur
          @team_grostitre = @match_une.teams.first.club.name
        elsif
          @team_grostitre_denominateur = @match_une.teams.second.club.denominateur
          @team_grostitre = @match_une.teams.second.club.name
        end
      end
  end

  def special_teams
    if @match_une.teams.first.status == 'draw'
      @grostitre = "Un match bien terne" if @match_une.teams.first.score = 0
      @grostitre = "Match nul" if @match_une.teams.first.score > 0
      @grostitre = "Un match fou !" if @match_une.teams.first.score > 2
    elsif @match_une.teams.first.status != 'draw'
      @team_grostitre = @match_une.teams.where("status = 'winner'").first.club.name
      @team_grostitre_loser = @match_une.teams.where("status = 'loser'").first.club.name

      @grostitre = "La Belgique a le seum" if @team_grostitre_loser === "Belgique"
      @grostitre = "Une victoire innatendue !" if @team_grostitre === "Suède"
      @grostitre = "Une avalanche de buts !" if @match_une.teams.where("status = 'winner'").first.score > 5
    end
  end

  def special_score
    @difference_buts = (@match_une.teams.first.score - @match_une.teams.last.score).abs
    p @difference_buts

    if @difference_buts > 5
      @grostitre = "Ca pique !"
    end
  end

  def administration
    if User.first.admin = false
      u1 = User.first
      u1.admin = true
      u1.save
    end
  end


  def maj_mode_for_matches
    Match.all.where(mode: nil).each { |m|
      m.mode = "Normal"
      m.save
    }
    redirect_to all_matches_path
  end

  def maj_tourn_format
    Tournament.all.each { |trn|
      trn.format = "Championnat"
      trn.save
    }
    redirect_to root_path
  end

  def maj_teams_status
    @matchacorriger = Array.new
    Team.all.where(status: nil).each { |t|
      @matchacorriger << t.match
    }
    p @matchacorriger.uniq
    @matchacorriger.uniq.each { |match|
      
      if ((match.teams.first.score > match.teams.last.score) && !match.prolongations)
          match.teams.first.update_columns(status: "winner")
          match.teams.last.update_columns(status: "loser")
      elsif ((match.teams.first.score < match.teams.last.score) && !match.prolongations)
          match.teams.first.update_columns(status: "loser")
          match.teams.last.update_columns(status: "winner")

      elsif match.prolongations && (match.teams.first.score > match.teams.last.score)
          match.teams.first.update_columns(status: "winner")
          match.teams.last.update_columns(status: "loser")
      elsif match.prolongations && (match.teams.first.score < match.teams.last.score)
          match.teams.first.update_columns(status: "loser")
          match.teams.last.update_columns(status: "winner")
      elsif (match.teams.first.score == match.teams.last.score) && (match.teams.first.prol_score > match.teams.last.prol_score)
          match.prolongations = true
          match.teams.first.update_columns(status: "winner")
          match.teams.last.update_columns(status: "loser")
      elsif (match.teams.first.score == match.teams.last.score) && (match.teams.first.prol_score < match.teams.last.prol_score)
          match.prolongations = true
          match.teams.first.update_columns(status: "loser")
          match.teams.last.update_columns(status: "winner")

      elsif ((match.teams.first.score == match.teams.last.score) && (match.teams.first.prol_score.nil))
          match.teams.first[:status] = "draw"
          match.teams.last[:status] = "draw"

      end
      match.save
      p match.id
      p match.teams.first[:status]
      p match.teams.last[:status]


    }
    redirect_to root_path
  end

=begin

  def goal_count
    @player.goals = Team.all.where("player_id='#{@player.id}'").sum(:score)
  end

  def pourcent_games(value)
    new_value = (value /= player.teams.count)
    new_value *= 100
  end

=end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/administration.html.erb
<h1>Administration</h1>

<br>Nombre d'utilisateurs enregistrés : <%=User.count%>
<br>Nombre de joueurs enregistrés : <%= Player.count%>
<br>Nombre de tournois créés : <%= Tournament.count%>
<br>Nombre de matchs créés : <%= Match.count%>
<br>Nombre de commentaires : <%= Comment.count%>
<br>
<br>Nombre de clubs paramétrés : <%=Club.count%>
<br>
<br>
<br>Liste des utilisateurs enregistrés :
<br><% User.all.each { |user| %>
<%= user.username %>, <%= user.admin %>
<br>
<% } %>
<br>
<br>Verifications Mise à jour vers version 2.0: OK
<br>
<br>Commencer par créer un tournoi
<br><%= link_to "MAJ Matchs => Ajout tournoi (désactivé)", root_path%>
<br><%= link_to "MAJ Teams => Ajout season_id (désactivé)", root_path%>
<br><%= link_to "MAJ Seasons => Ajout player stats (désactivé)", root_path%>
<br>
<br>A faire en 2e étape, retrait des colonnes inutilisées sur Player.
<br>

<br>MAJ 03-04/2019 : Ajout mode normal pour matchs sans mode (2018) et MAJ Format des tournois deja crees
<br><%= link_to "MAJ Matchs sans mode (désactivé)", root_path%>
<br><%= link_to "MAJ Tournois sans format (désactivé)", root_path%>
<br><%= link_to "MAJ Equipes sans status (désactivé)", root_path%>

app/views/home/all_matches.html.erb
<h1>Tous les matchs</h1>
<div class="title_w_bg">Liste des matchs joués</div>

<table class="scoreboard">
  <tr>
    <th>ID du match</th>
    <th>Compétiton</th>
    <th>Joueur 1</th>
    <th>Team 1</th>
    <th>Score</th>
    <th>Team 2</th>
    <th>Joueur 2</th>
    <th>Mode</th>
  </tr>
  <br>
  <% if @matches.count == 0 %>
    <tr> <td> Pas de match enregistré </td> </tr>
  <% else %>
    <% @matches.order('id DESC').each do |match| %>
      <% if match.teams.empty? %>
      <tr>
        <td><%= match.id %></td>
        <td>....</td>
        <td><%= link_to 'Supprimer', match_path(match), method: :delete,
                data: { confirm: 'Etes vous sur ?' }%></td>

      </tr>
      <% else %>
      <tr>
        <td><%= match.id %></td>
        <td><%= match.tournament.name %></td>
        <td><%= link_to Player.find(match.teams.first.player_id).pseudo, player_path(match.teams.first.player_id) %> </td>
        <td><%= match.teams.first.club.name %> </td>
        <td><div class="tab_score">
              <%= match.teams.first.score %> - <%= match.teams.last.score %>
            </div>
            <span class="tab_score_prol">
            <%= (match.prolongations && !match.teams.first.prol_score) ? "a.p" : "" %>
            <%= match.teams.first.prol_score %><%= match.teams.first.prol_score == nil ? '' : ' tab ' %><%= match.teams.last.prol_score %>
            </span>
        </td>

        <td><%= match.teams.last.club.name %> </td>
        <td><%= link_to Player.find(match.teams.last.player_id).pseudo, player_path(match.teams.last.player_id) %> </td>
        <td><%= match.mode%></td>
        <td><%= link_to "Détails", match_path(match)%></td>
        <% if user_signed_in? %>
          <td><%= link_to "Modifier", edit_match_path(match)%></td>
          <td><%= link_to 'Supprimer', match_path(match), method: :delete,
                  data: { confirm: 'Etes vous sur ?' }%></td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  <% end %>
</table>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/home/index.html.erb
<% if !mobile_device? && !@grostitre.nil?%>
<h1 class="mobile-content_une"><%=@match_une.tournament.name%></h1>
<% end %>

<div class="main_content_4_8">
  <div class="main_left">
    <% if @matches.count != 0 %>

      <% if !mobile_device? %>
        <% if @matches.count != 0 %>
          <div class="grostitre">
            <% if !@grostitre.nil? %>
              <%= @grostitre %>
            <% else  %>
              <%= @team_grostitre_denominateur.nil? ? "" : @team_grostitre_denominateur %> <%= @team_grostitre %> l'emporte
            <% end %>
          </div>
        <% else %>
          <div class="grostitre">
            Pas de match rencontre
          </div>
        <% end %>
        <% if @matches.count != 0 %>
        <div class="title_w_bg title_une">A la une
          <div class="title_tournament"><%= @match_une.tournament.name %></div>
          <div class="title_journee"><%= @match_une.tournament.matches.count %>e journée</div>
        </div>
        <% end %>
      <% end %>

      <div class="image_une">
        <%= link_to image_tag(@image_a_la_une, size: "700x416", alt: "Illustration"), match_path(@match_une)%>
      </div>
      <div class="score_une">
          <tr>
            <div class="mobile-player_une">
              <% if mobile_device? %><!-- Afficher d'abord l'equipe sur mobile -->
                <td><%= @match_une.teams.first.club.name %> </td>
              <% end %>
              <td><span class="tab_player">
                <%= @match_une.teams.first.player.pseudo %> </td>
              </span></td>
              <% if !mobile_device? %><!-- Afficher l'equipe après le joueur sur ordi -->
                <td><%= @match_une.teams.first.club.name %> </td>
              <% end %>
            </div>
            <td>
              <div class="tab_score_une">
                  <div class="tab_score_one <%= 'winner' if @match_une.teams.first.status == 'winner' %>">
                    <%= @match_une.teams.first.score %>
                  </div>
                  <div class="tab_score_two <%= 'winner' if @match_une.teams.last.status == 'winner' %>">
                    <%= @match_une.teams.last.score %>
                  </div>
              </div>
            </td>
            <div class="mobile-player_une">
              <td><%= @match_une.teams.last.club.name %></td>
              <td><span class="tab_player">
                  <%= @match_une.teams.last.player.pseudo %>
                  </span>
              </td>
            </div>

          </tr>
      </div>
      <% if mobile_device? %>
        <div class="grostitre_une">
          <% if mobile_device? %>
            A la une | <%= @match_une.tournament.matches.count %>e journée
          <% end %>
          <div class="grostitre_mobile">
            <% if !@grostitre.nil? %>
              <%= @grostitre %>
            <% else  %>
              <%= @team_grostitre_denominateur.nil? ? "" : @team_grostitre_denominateur %> <%= @team_grostitre %> l'emporte
            <% end %>
          </div>
        </div>
      <% end %>

    <% end %>

    <br>
    <% if !@match_une.nil? %>
        <div class="match_une_links mobile-content_une"> <%= link_to ">  Voir la compétition", tournament_path(@match_une.tournament) %>
          <%= link_to ">  Le résumé du match", match_path(@match_une) %>
        </div>
    <% end %>
    <br>

    <div class="title_w_bg">Les 5 derniers matchs</div>

    <table class="scoreboard">

      <% if @matches.count == 0 %>
        <tr> <td> Pas de match enregistré </td> </tr>
      <% elsif @match_une.tournament.matches.count > 1 %>
              <tr>
                <th>Mode</th>
                <th>J1</th>
                <th>Team 1</th>
                <th>Score</th>
                <th>Team 2</th>
                <th>J2</th>
              </tr>
              <br>

              <% @match_une.tournament.matches.order(id: :desc).first(5).each do |match| %>
                <% if match.teams.empty? %>
                <tr>
                  <td><%= match.id %></td>
                  <td>....</td>
                  <td><%= link_to 'Supprimer', match_path(match), method: :delete,
                          data: { confirm: 'Etes vous sur ?' }%></td>

                </tr>
                <% else %>
                <tr>
                  <td><%= match.mode %></td>
                  <td><span class="tab_player">
                    <%= link_to Player.find(match.teams.first.player_id).pseudo, player_path(match.teams.first.player_id) %> </td>
                  </span></td>

                  <% if match.teams.first.status == "winner" %><td class="statuswinner">
                    <% else %><td>
                  <% end %>
                  <%= match.teams.first.club.name %> </td>
                  <td><div class="tab_score">
                        <%= match.teams.first.score %> - <%= match.teams.last.score %>
                      </div>
                      <span class="tab_score_prol">
                      <%= (match.prolongations && !match.teams.first.prol_score) ? "a.p" : "" %>
                      <%= match.teams.first.prol_score %><%= match.teams.first.prol_score == nil ? '' : ' tab ' %><%= match.teams.last.prol_score %>
                      </span>
                  </td>
                  <% if match.teams.last.status == "winner" %><td class="statuswinner">
                    <% else %><td>
                  <% end %>
                  <%= match.teams.last.club.name %></td>
                  <td><span class="tab_player">
                      <%= link_to Player.find(match.teams.last.player_id).pseudo, player_path(match.teams.last.player_id) %>
                      </span>
                  </td>

                  <td><%= link_to "Détails", match_path(match)%></td>
                  <% if user_signed_in? %><td><%= link_to "Modifier", edit_match_path(match)%></td><% end %>
                 </tr>
                 <% end %>
              <% end %>
      <% else %>
      <br>Pour l'instant, cette compétition n'a pas d'autre match.
      <% end %>
    </table>

    <br>

    <div class="title_w_bg">Classement </div>
    <% if @matches.count != 0 %>

    <table class="leaderboard mobile-content_une">
      <tr>
        <th> </th>
        <th> </th>
        <th>Pts</th>
        <th>J.</th>
        <th>G.</th>
        <th>G.pr</th>
        <th>G.pn.</th>
        <th>N.</th>
        <th>D.</th>
        <th>D.pr</th>
        <th>D.pn.</th>
        <th class="lb_br">Diff.</th>
      </tr>
      <br>

      <% i = 0
        @match_une.tournament.seasons.order(points: :desc).each do |season|
        i = i+1.to_i
      %>
        <tr>
          <td><%= i %></td>
          <td class="lead_team"><%= link_to season.player.pseudo, player_path(season.player) %></td>
          <td><b><%= season.points %></b></td>
          <td class="lb_br"><%= season.teams.count %> </td>
          <td><%= season.win %> </td>
          <td><%= season.win_prol %> </td>
          <td class="lb_br"><%= season.win_peno %> </td>
          <td class="lb_br"><%= season.draw %> </td>
          <td><%= season.lose %> </td>
          <td><%= season.lose_prol %> </td>
          <td class="lb_br"><%= season.lose_peno %> </td>
          <td class="lb_br"><%= (Team.all.where("season_id= '#{season.id}'").sum(:score))-((Team.where("season_id= '#{season.id}'").collect{|a| a.match.teams.collect{|b| b.score}.sum }.sum)-(Team.all.where("season_id= '#{season.id}'").sum(:score))) %>
        </tr>
      <% end %>
    <% end %>

    </table>
    <br>
    <div class="title_w_bg">Reglement en vigueur </div>
    <% if @matches.count != 0 %>
    <ul class="list_rules mobile-content_une">
      <li>Match gagné : +<%= @match_une.tournament.win_regular_points %>
      <li>Match gagné après prolongations : +<%= @match_une.tournament.win_prol_points %>
      <li>Match gagné aux penalties : +<%= @match_une.tournament.win_peno_points %>
      <li><% if (@match_une.tournament.lose_regular_points && @match_une.tournament.lose_prol_points && @match_une.tournament.lose_peno_points) == 0 %>
          Pas de point pour le perdant.
        <% end %>
      <li>Match nul : +<%= @match_une.tournament.draw_regular_points %>

    </ul>
    <% end %>

  </div>

  <div class="main_right">
    <div class="title_w_bg">Le vestiaire </div>
    <br>

    <table class="commentboard mobile-content_une">
      <% if @comments.count == 0 %>
        <div class="mobile-content_une">
          Pas de commentaire
        </div>
      <% else %>
        <% @comments.order("created_at DESC").each do |comment| %>
          <tr>
            <td class="comment_time"><%= comment.created_at.strftime("%H:%M") %></td>
            <td class="comment_content"><span class="comment_user"><%= comment.user.username %></span> : <%= comment.content %> </td>
          </tr>
        <% end %>
      <% end %>
    </table>
    <br>
    <div class="new_comment mobile-content_une">
      <% if user_signed_in? %>
          <%= form_for(Comment.new) do |com| %>
            <div class="field">
              <%= com.text_field :content, placeholder: "Commentaire" %>
            </div>
            <div class="actions">
              <%= com.submit "Envoyer" %>
            </div>
          <% end %>
      <% else %>
          <i>Vous devez être connecté pour pouvoir commenter.</i>
      <% end %>
    </div>
  </div>

</div>

<script type="text/javascript">
console.log(isMobileDevice());
</script>

app/views/home/leaderboard.html.erb
<h1>FIFA 18</h1>

<div class="title_w_bg">Classement et statistiques </div>

<table class="leaderboard">
  <tr>
    <th> </th>
    <th> </th>
    <th>Pts</th>
    <th>J.</th>
    <th>G.</th>
    <th>G.pr</th>
    <th>G.pn.</th>
    <th>D.</th>
    <th>D.pr</th>
    <th>D.pn.</th>
    <th>Diff.</th>
    <th>bp.</th>
    <th class="lb_br">bc.</th>
  </tr>
  <br>

  <% i = 0
    @players.order(points: :desc).each do |player|
    i = i+1.to_i
  %>
    <tr>
      <td><%= i %></td>
      <td class="lead_team"><%= player.pseudo %></td>
      <td><b><%= player.points %></b></td>
      <td class="lb_br"><%= player.teams.count %> </td>
      <td><%= player.win %> </td>
      <td><%= player.win_prol %> </td>
      <td class="lb_br"><%= player.win_peno %> </td>
      <td><%= player.lose %> </td>
      <td><%= player.lose_prol %> </td>
      <td class="lb_br"><%= player.lose_peno %> </td>
      <td><%= (Team.all.where("player_id= '#{player.id}'").sum(:score))-((Team.where("player_id= '#{player.id}'").collect{|a| a.match.teams.collect{|b| b.score}.sum }.sum)-(Team.all.where("player_id= '#{player.id}'").sum(:score))) %>
      <td><%= Team.all.where("player_id= '#{player.id}'").sum(:score) %></td>
      <td class="lb_br"><%= (Team.where("player_id= '#{player.id}'").collect{|a| a.match.teams.collect{|b| b.score}.sum }.sum)-(Team.all.where("player_id= '#{player.id}'").sum(:score)) %></td>
    </tr>
  <% end %>

</table>


<div class="title_w_bg">Statistiques : Ratios par match </div>

<table class="leaderboard">
  <tr>
    <th> </th>
    <th> </th>
    <th>Pts / match</th>
    <th>Matchs<br>joués</th>
    <th>G.</th>
    <th>G.pr</th>
    <th>G.pn.</th>
    <th>D.</th>
    <th>D.pr</th>
    <th>D.pn.</th>
    <th class="lb_br">Buts /<br>match</th>
    <th class="lb_br">Bc./<br>match</th>
  </tr>
  <br>

  <% i = 0
    @players.order(points: :desc).each do |player|
    i = i+1.to_i
  %>
    <tr>
      <td><%= i %></td>
      <td class="lead_team"><%= player.pseudo %></td>
      <td class="lb_br"><b><%= (player.points.to_f/ player.teams.count).round(2)%></b></td>
      <td class="lb_br"><%= player.teams.count %> </td>

      <td>              <%= number_to_percentage(((100 * player.win) / player.teams.count), precision: 0) %> </td>
      <td>              <%= number_to_percentage(((100 * player.win_prol)/ player.teams.count), precision: 0) %> </td>
      <td class="lb_br"><%= number_to_percentage(((100 * player.win_peno) / player.teams.count), precision: 0) %> </td>
      <td>              <%= number_to_percentage(((100 * player.lose) / player.teams.count), precision: 0) %> </td>
      <td>              <%= number_to_percentage(((100 * player.lose_prol) / player.teams.count), precision: 0) %> </td>
      <td class="lb_br"><%= number_to_percentage(((100 * player.lose_peno) / player.teams.count), precision: 0) %> </td>
      <td><%= (Team.all.where("player_id= '#{player.id}'").sum(:score).to_f / player.teams.count).round(2) %></td>
      <td class="lb_br"><%= (((Team.where("player_id= '#{player.id}'").collect{|a| a.match.teams.collect{|b| b.score}.sum }.sum)-(Team.all.where("player_id= '#{player.id}'").sum(:score))).to_f / player.teams.count).round(2) %></td>
    </tr>
  <% end %>

</table>

<div class="title_w_bg">Légende </div>
<br> Pts = Points
<br> J. = Matchs joués
<br> G. = Matchs gagnés
<br> G.pr = Matchs gagnés après prolongations
<br> G.pn = Matchs gagnés aux penalties
<br>
<br> Diff. = Différence de buts
<br> bp. = Buts pour
<br> bc. = Buts contre