config/routes.rb
Rails.application.routes.draw do

  get 'seasons/new'

  get 'seasons/show'

  root 'home#index'
  get '/touslesmatchs', to: 'home#all_matches', as: 'all_matches'
  get '/touslesclubs', to: 'clubs#all_clubs', as: 'all_clubs'
  get '/allseasons', to: 'seasons#all_seasons', as: 'all_seasons'
  get '/admin', to: 'home#administration', as: 'admin'

  get '/admin/maj_mode', to: 'home#maj_mode_for_matches', as: 'admin_maj_mode'
  get '/admin/maj_tournament_format', to: 'home#maj_tourn_format', as: 'admin_maj_tournament_format'
  get '/admin/maj_teams_status', to: 'home#maj_teams_status', as: 'admin_maj_teams_status'

  get '/classement', to: 'home#leaderboard', as: 'leaderboard'
  get '/randomiser', to: 'matches#randomiser', as: 'alea_match'

  resources :matches do
    collection do
      get 'populate_other_list'
    end
  end

  resources :tournaments
  get '/competitions', to: 'tournaments#all_tournaments', as: 'all_tournaments'
  get '/tournaments/:id/launched', to: 'tournaments#close_inscriptions', as: 'close_inscriptions'
  get '/tournaments/:id/closed', to: 'tournaments#close_tournament', as: 'close_tournament'
  get '/tournaments/:id/opened', to: 'tournaments#open_tournament', as: 'open_tournament'
  get '/all_matches/maj', to: 'matches#maj_tournament_for_matches', as: 'maj_tournament'

=begin
  get '/competitions/maj', to: 'tournaments#migrate_all_existing_matches_to_last_season', as: 'maj_teams_season'
  get '/competitions/maj_stats', to: 'tournaments#migrate_all_player_stats_to_last_season_stats', as: 'maj_seasons_stats'
=end

  resources :teams
  resources :players
  resources :clubs
  resources :comments
  resources :seasons

  devise_for :users,
      path: '',
      controllers: {
         sessions: "users/sessions",
         registrations: "users/registrations" },
      path_names: {
        sign_in: 'login',
        sign_out: 'logout',
        sign_up: 'register',
        edit: 'settings',
      }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord

  has_many :teams
  validates :name, uniqueness: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, foreign_key: "user_id"
  validates_length_of :content, :maximum => 100
end

app/models/match.rb
class Match < ApplicationRecord

  validates :tournament_id, presence: true

  has_many :teams, dependent: :destroy
  accepts_nested_attributes_for :teams,
    allow_destroy: true,
    reject_if: :all_blank

  has_many :players, :through => :teams
  accepts_nested_attributes_for :players

  has_many :clubs, :through => :teams
  accepts_nested_attributes_for :clubs

  belongs_to :tournament, foreign_key: "tournament_id"
  belongs_to :round, optional: true, foreign_key: "round_id"
end

app/models/player.rb
class Player < ApplicationRecord

  has_many :teams
  has_many :matches

  validates :pseudo, uniqueness: true

  has_many :seasons
  has_many :tournament, :through => :seasons

end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :tournament, foreign_key: "tournament_id"
  has_many :matches, dependent: :destroy

  has_many :roundteams, dependent: :destroy
  has_many :seasons, :through => :roundteams
end

app/models/roundteam.rb
class Roundteam < ApplicationRecord
  belongs_to :round, optional: true, foreign_key: "round_id"
  belongs_to :season, optional: true, foreign_key: "season_id"
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :player, optional: true, foreign_key: "player_id"
  belongs_to :tournament, optional: true, foreign_key: "tournament_id"

  has_many :roundteams, dependent: :destroy
  accepts_nested_attributes_for :roundteams,
    allow_destroy: true,
    reject_if: :all_blank

  has_many :rounds, :through => :roundteams
  accepts_nested_attributes_for :rounds

  has_many :teams

end

app/models/team.rb
class Team < ApplicationRecord

  belongs_to :match, optional: true, foreign_key: "match_id"
  belongs_to :season, optional: true, foreign_key: "season_id"
  belongs_to :player, optional: true, foreign_key: "player_id"
  belongs_to :club, optional: true, foreign_key: "club_id"

  validates :club, presence: true
  validates :score,
            :presence => {:message => "Le nombre de buts n'est pas indiqué." },
            :numericality => {:greater_than_or_equal_to => 0 , :message => "Le nombre de buts doit être positif." }



end

app/models/tournament.rb
class Tournament < ApplicationRecord

  validates :name, presence: true, uniqueness: true
  validates :format, presence: true

  has_many :matches, dependent: :destroy

  has_many :rounds, dependent: :destroy
  accepts_nested_attributes_for :rounds, allow_destroy: true

  has_many :seasons, dependent: :destroy
  accepts_nested_attributes_for :seasons, allow_destroy: true

  has_many :players, :through => :seasons
  accepts_nested_attributes_for :players

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  validates :username, presence: true, uniqueness: true

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def link_to_add_player_fields(name, s, association)
    new_object = s.object.send(association).klass.new
    id = new_object.object_id
    fields = s.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", s: builder)
    end
    link_to(name, '#', class: "add_player_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <a href="https://github.com/nicohc">Un site réalisé par NicoHC </a> - 2018 - Ruby on Rails 5
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
    <% if !mobile_device? && current_page?(root_path) %>
    <div id="site_title"><%= link_to "La compète", root_path %>
    </div>
    <% end %>
    <nav>
      <ul class="main-menu"><!-- Menu principal normal -->
        <div>
          <li><%= link_to content_tag(:i, nil, class: 'fas fa-home'), root_path %></li>
          <li id="site_title_fixed"><%= link_to "La compète", root_path %></li>
          <li class="principal_item"><%= link_to "Liste des Compétitions", all_tournaments_path %>
            <% if Tournament.count > 1 %>
                <ul class="sous_menu">
                <% Tournament.order('id DESC').first(3).each { |t| %>
                  <li><%= link_to t.name, tournament_path(t) %></li>
                <% } %>
                </ul>
            <% end %>
          </li>
          <li><%= link_to "Liste des Matchs", all_matches_path %> </li>
        </div>
        <div>
        <li class="divider"></li>
        <li><%= link_to "Nouveau match", new_match_path %> </li>
        <li><%= link_to "Créateur de match", alea_match_path %> </li>
        <% if user_signed_in? %>
          <li class="dropdown">Paramètres

            <ul class="dropdown-menu">
              <li><%= link_to "Nouveau joueur", new_player_path %> </li>
              <li><%= link_to "Nouveau club", new_club_path %> </li>
              <li><%= link_to "Liste des clubs", all_clubs_path %> </li>
              <li><%= link_to "Modifier mon compte", edit_user_registration_path %>
              </li>
              <% if current_user.admin %>
                <li><%= link_to "Administration", admin_path %></li>
                <li><%= link_to "Saisons", all_seasons_path %></li>

              <% end %>

              <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete  %>
              </li>
            </ul>
          </li>
        </div>
        <% else%>
            <li><%= link_to content_tag(:i, nil, class: 'far fa-user'), new_user_session_path %>
            </li>
        <% end %>


      </ul>
      <% if mobile_device? %>

        <div id="site_title_mobile"><%= link_to "La compète", root_path %>
        <div class="menu-symbol">
          <i class="fas fa-bars"></i>
        </div>
        <ul class="mobile-menu" style="display:none;"><!-- Menu mobile -->
          <li><%= link_to "Accueil", '/' %></li>
          <li><%= link_to "Liste des Compétitions", all_tournaments_path %></li>
          <li><%= link_to "Liste des Matchs", all_matches_path %> </li>
          <li class="divider"></li>
          <li><%= link_to "Nouveau match", new_match_path %> </li>
          <li><%= link_to "Créateur de match", alea_match_path %> </li>
          <% if user_signed_in? %>
            <li class="dropdown">Paramètres
                <li><%= link_to "Nouveau joueur", new_player_path %> </li>
                <li><%= link_to "Nouveau club", new_club_path %> </li>
                <li><%= link_to "Liste des clubs", all_clubs_path %> </li>
                <li><%= link_to "Modifier mon compte", edit_user_registration_path %>
                </li>
                <li><%= link_to "Administration", admin_path %></li>

                <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete  %>
                </li>
            </li>

          <% else%>
              <li><%= link_to "Se connecter", new_user_session_path %>
              </li>
          <% end %>
        </ul> <!-- FIN Menu mobile -->
      <% end %>

    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compete</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <%= favicon_link_tag asset_path('faviconC.png'), :rel => 'icon', :type =>  'image/png' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin:400,400i,800,800i" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">
      <div class="main_content">
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_new_match.html.erb
<% if @match.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Le formulaire contient <%= pluralize(@match.errors.count, "error") %>.
    </div>
    <ul>
    <% @match.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>